### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by BelongVolc** [iMED-Lab/UG-GAT#1]
Hello, I'd like to ask about the data set. We learned from your code and encountered some problems. What kind of data is returned by getpathandlabel in datasetgraphcla class and what data is stored in pathlist. If it's convenient for you, please clear the key data and send your data set file and generated file, My email address is zmd211060006@163.com. Thank you very much.

**Comment by JinkuiH** [comment]
Sorry for the late reply. getpathandlabel function in datasetgraphcla class returns the data path for GNN, i.e., feature and uncertainty generated by BayesianCNN, and corresponding label.
